import type { SiteConfig } from '../types';

export const SITE_CONFIG: SiteConfig = {
  whatsapp: "917770033326",
  domain: "https://aeroxebroadband.com",
  location: {
    mapUrl: "https://maps.app.goo.gl/gZXzQKuHh6rcp55Q8?g_st=aw",
    city: "Jalgaon",
    state: "Maharashtra",
    country: "India",
  },
  company: {
    name: "AeroXe Broadband",
    legalName: "Aeroxe Enterprises Pvt. Ltd.",
    tagline: "Lightning Fast Fiber Internet",
    description: "Premium fiber optic internet services in Jalgaon, Maharashtra. Reliable, fast, and affordable connectivity solutions for home and business.",
    phone: "+91 77700 33326",
    email: "support@aeroxe.com",
    address: "Jalgaon, Maharashtra, India",
  },
  social: {
    facebook: "https://facebook.com/aeroXe",
    twitter: "https://twitter.com/aeroXe",
    instagram: "https://instagram.com/aeroXe",
    linkedin: "https://linkedin.com/company/aeroXe",
    youtube: "https://youtube.com/@aeroXe",
  },
  navLinks: [
    { label: "Home", href: "/" },
    { label: "Plans", href: "/plans" },
    { label: "Coverage", href: "/check-availability" },
    { label: "About", href: "/about" },
    { label: "Support", href: "/support" },
    { label: "Contact", href: "/contact" },
  ],
  plans: [
    {
      id: "basic-50",
      speed: "50 Mbps",
      speedMbps: 50,
      tag: "Basic",
      popular: false,
      durations: {
        1: { price: 400, label: "1 Month" },
        3: { price: 1150, label: "3 Months", savings: "Save ₹50" },
        6: { price: 2250, label: "6 Months", savings: "Save ₹150" },
        12: { price: 4300, label: "12 Months", savings: "Save ₹500" },
      },
      features: ["Unlimited Data", "Free Installation", "24/7 Support", "Reliable Connection"],
    },
    {
      id: "standard-100",
      speed: "100 Mbps",
      speedMbps: 100,
      tag: "Standard",
      popular: true,
      durations: {
        1: { price: 600, label: "1 Month" },
        3: { price: 1700, label: "3 Months", savings: "Save ₹100" },
        6: { price: 3350, label: "6 Months", savings: "Save ₹250" },
        12: { price: 6400, label: "12 Months", savings: "Save ₹800" },
      },
      features: ["Unlimited Data", "Free Installation", "24/7 Support", "Reliable Connection", "Dual Band WiFi Router Free*"],
    },
    {
      id: "premium-150",
      speed: "150 Mbps",
      speedMbps: 150,
      tag: "Premium",
      popular: false,
      durations: {
        1: { price: 800, label: "1 Month" },
        3: { price: 2300, label: "3 Months", savings: "Save ₹100" },
        6: { price: 4550, label: "6 Months", savings: "Save ₹250" },
        12: { price: 8700, label: "12 Months", savings: "Save ₹900" },
      },
      features: ["Unlimited Data", "Free Installation", "24/7 Support", "Reliable Connection", "Dual Band WiFi Router Free*", "Priority Support"],
    },
    {
      id: "pro-200",
      speed: "200 Mbps",
      speedMbps: 200,
      tag: "Pro",
      popular: false,
      durations: {
        1: { price: 1000, label: "1 Month" },
        3: { price: 2850, label: "3 Months", savings: "Save ₹150" },
        6: { price: 5650, label: "6 Months", savings: "Save ₹350" },
        12: { price: 10800, label: "12 Months", savings: "Save ₹1200" },
      },
      features: ["Unlimited Data", "Free Installation", "24/7 Support", "Reliable Connection", "Dual Band WiFi Router Free*", "Priority Support"],
    },
    {
      id: "ultimate-300",
      speed: "300 Mbps",
      speedMbps: 300,
      tag: "Ultimate",
      popular: false,
      durations: {
        1: { price: 1300, label: "1 Month" },
        3: { price: 3700, label: "3 Months", savings: "Save ₹200" },
        6: { price: 7350, label: "6 Months", savings: "Save ₹450" },
        12: { price: 14000, label: "12 Months", savings: "Save ₹1600" },
      },
      features: ["Unlimited Data", "Free Installation", "24/7 Support", "Reliable Connection", "Dual Band WiFi Router Free*", "Priority Support", "Business Grade"],
    },
  ],
  features: [
    { icon: "Zap", title: "High Speed Fiber", description: "Blazing-fast internet with speeds up to 300 Mbps over fiber optic. Perfect for streaming, gaming, video calls, and remote work." },
    { icon: "Infinity", title: "Unlimited Internet", description: "No data caps, no FUP limits, no throttling. Enjoy truly unlimited internet access on all your devices." },
    { icon: "Monitor", title: "Free WiFi Router", description: "Get a free Dual Band WiFi router with 12-month plans. Enjoy strong, stable WiFi coverage throughout your home or office." },
    { icon: "Headphones", title: "24/7 Support", description: "Round-the-clock customer support via phone and WhatsApp. We're always here when you need us." },
    { icon: "Zap", title: "Free Installation", description: "Professional free installation by our expert technicians. Limited period offer." },
    { icon: "Shield", title: "Reliable Connection", description: "Enterprise-grade reliability with redundant fiber backbone for consistent connectivity." },
    { icon: "BadgePercent", title: "Affordable Plans", description: "Premium internet at the most competitive prices. Plans starting from just ₹400/month." },
    { icon: "Globe", title: "Local Service", description: "Proudly serving Jalgaon with personalized local support." },
  ],
  whyChooseUs: [
    { title: "Free Installation", description: "Limited period offer — get connected absolutely free. No installation or setup charges." },
    { title: "Free Dual Band Router", description: "12-month plans include a complimentary Dual Band WiFi router for seamless connectivity." },
    { title: "Enterprise Reliability", description: "Reliable fiber optic network with redundant backbone for uninterrupted internet." },
    { title: "No FUP Limits", description: "No hidden caps. Stream, download, and browse as much as you want." },
    { title: "Affordable Pricing", description: "Competitive plans starting at just ₹400/month. Save more with our longer duration plans." },
    { title: "24/7 Local Support", description: "Expert support team based in Jalgaon, available anytime via phone or WhatsApp." },
    { title: "Fiber Backbone", description: "Modern fiber optic infrastructure delivering consistent high-speed connectivity." },
  ],
  installationSteps: [
    { step: 1, title: "Contact Us", description: "Call or WhatsApp us at 77700 33326, or fill out our contact form to get started." },
    { step: 2, title: "Verification", description: "We verify your address in Jalgaon and surrounding areas to confirm coverage availability." },
    { step: 3, title: "Free Installation", description: "Our expert technicians visit your premises and install the fiber connection at no cost." },
    { step: 4, title: "Activation", description: "Your connection is activated instantly. Start enjoying high-speed fiber internet immediately." },
  ],
  testimonials: [
    { name: "Rahul Sharma", role: "Remote Professional, Jalgaon", feedback: "AeroXe Broadband has been a game-changer for my work-from-home setup. The 100 Mbps plan is rock solid and I've never faced a single disconnection in 3 months!", rating: 5 },
    { name: "Priya Patil", role: "College Student", feedback: "Finally, reliable internet in Jalgaon! No more buffering during online classes. The free WiFi router works great throughout our home. Highly recommended!", rating: 5 },
    { name: "Amit Deshmukh", role: "Small Business Owner", feedback: "Our entire business runs on AeroXe Broadband's 200 Mbps connection. Video calls are crystal clear, and their support team is incredibly responsive.", rating: 5 },
    { name: "Sneha Joshi", role: "Streaming Enthusiast", feedback: "4K streaming on Netflix and Prime Video without any buffering — even with multiple devices connected. AeroXe Broadband is the best ISP in Jalgaon, hands down.", rating: 5 },
    { name: "Vikram Singh", role: "Gamer, Jalgaon", feedback: "Low ping, consistent speeds, and zero lag in competitive games. The 150 Mbps plan is perfect for gaming. Plus, the free installation was quick and clean!", rating: 5 },
  ],
  faqs: [
    { question: "How quickly can I get internet installed in Jalgaon?", answer: "We typically install within 24-48 hours of your request. In many areas of Jalgaon, same-day installation is available. Plus, installation is absolutely free for a limited period!" },
    { question: "What internet speeds do you offer?", answer: "We offer fiber optic plans from 50 Mbps to 300 Mbps. All plans provide symmetrical speeds and truly unlimited data with no FUP limits." },
    { question: "How do I contact customer support?", answer: "Our support team is available 24/7 via phone at 77700 33326, WhatsApp at the same number, or through our website contact form." },
    { question: "What internet plans do you have?", answer: "We have 5 speed tiers: 50 Mbps (₹400/mo), 100 Mbps (₹600/mo), 150 Mbps (₹800/mo), 200 Mbps (₹1,000/mo), and 300 Mbps (₹1,300/mo)." },
    { question: "Is AeroXe Broadband available in my area?", answer: "We are currently serving Jalgaon with plans to expand to Bhusawal, Mumbai, Navi Mumbai, and Barhanpur soon." },
    { question: "Do I get a free WiFi router?", answer: "Yes! All 12-month plans include a complimentary Dual Band WiFi router for strong, stable WiFi coverage." },
    { question: "Is installation really free?", answer: "Yes, installation is completely free for a limited period. Our expert technicians set up everything at no cost to you." },
    { question: "What is fiber optic internet?", answer: "Fiber optic internet uses light signals through glass cables to deliver data at lightning speeds. It's faster and more reliable than traditional copper connections." },
    { question: "What payment methods do you accept?", answer: "We accept UPI (Google Pay, PhonePe, Paytm), net banking, and cash payments with flexible billing cycles." },
    { question: "Do you offer business internet plans?", answer: "Yes! Our 200 Mbps and 300 Mbps plans are ideal for businesses, offering priority support, static IP options, and guaranteed uptime." },
  ],
  coverageAreas: [
    { name: "Jalgaon", status: "active", type: "city", pincodes: ["425001", "425002", "425003", "425004", "425005"] },
    { name: "Bhusawal", status: "coming-soon", type: "city", pincodes: ["425101"] },
    { name: "Mumbai", status: "coming-soon", type: "city" },
    { name: "Navi Mumbai", status: "coming-soon", type: "city" },
    { name: "Barhanpur", status: "coming-soon", type: "city" },
    { name: "Jalgaon City Center", status: "active", type: "area", pincodes: ["425001", "425002"] },
    { name: "Shirpur Road", status: "active", type: "area", pincodes: ["425001"] },
    { name: "Mahabal", status: "active", type: "area", pincodes: ["425001"] },
    { name: "Ravivar Peth", status: "active", type: "area", pincodes: ["425001", "425002"] },
    { name: "Navipeth", status: "active", type: "area", pincodes: ["425001"] },
    { name: "Nagar Parishad", status: "active", type: "area", pincodes: ["425002"] },
    { name: "Bhusawal Road", status: "active", type: "area", pincodes: ["425003"] },
    { name: "MIDC Area", status: "active", type: "area", pincodes: ["425004"] },
    { name: "Railway Station Area", status: "active", type: "area", pincodes: ["425003", "425005"] },
  ],
  socialMedia: {
    facebook: "https://facebook.com/aeroXe",
    twitter: "https://twitter.com/aeroXe",
    instagram: "https://instagram.com/aeroXe",
    linkedin: "https://linkedin.com/company/aeroXe",
    youtube: "https://youtube.com/@aeroXe",
    whatsapp: "https://wa.me/917770033326",
  },
  keywords: {
    primary: [
      "fiber internet Jalgaon",
      "broadband provider Jalgaon",
      "high speed internet Jalgaon",
      "WiFi internet Jalgaon",
      "home internet Jalgaon",
    ],
    secondary: [
      "ISP Jalgaon",
      "business broadband Jalgaon",
      "unlimited internet Jalgaon",
      "fiber optic internet",
      "broadband service",
    ],
    locationKeywords: [
      "Jalgaon internet",
      "Jalgaon broadband",
      "internet service provider Maharashtra",
      "fiber internet provider India",
      "fastest broadband Jalgaon",
      "affordable internet Jalgaon",
      "unlimited data Jalgaon",
      "WiFi plans Jalgaon",
    ],
  },
  team: [
    {
    name: "Saif Ali",
    photo: "",
    designation: "Founder & Management",
    about:
      "Leads strategic growth and business direction with a strong focus on scalability, customer trust, and long-term value creation.",
  },
  {
    name: "Abdullah Shah",
    photo: "",
    designation: "Founder & Operations",
    about:
      "Ensures seamless execution across installations and service delivery, optimizing processes for speed, reliability, and customer satisfaction.",
  },
  {
    name: "Azaz Ali",
    photo: "",
    designation: "Founder & Network",
    about:
      "Designs and maintains high-performance broadband networks, ensuring consistent speed, low latency, and robust connectivity.",
  },
  {
    name: "Gajju Shah",
    photo: "",
    designation: "Founder & Optics Network Infra",
    about:
      "Specializes in fiber infrastructure deployment, building scalable and resilient optical networks for uninterrupted connectivity.",
  },
  {
    name: "Farhana Ali",
    photo: "",
    designation: "Founder & Software",
    about:
      "Develops intelligent systems and automation that power operations, enhance performance, and deliver a seamless digital experience.",
  },
  ],
};
